/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package copecgui;

/**
 *
 * @author Juan Capiz
 */
public class CopecFrame extends javax.swing.JFrame {

    /**
     * Creates new form CopecFrame
     */
    public CopecFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        WestPanel = new javax.swing.JPanel();
        Boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        CenterPanel = new javax.swing.JPanel();
        west = new javax.swing.JPanel();
        north = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        suth = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        East = new javax.swing.JPanel();
        North = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        South = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        south = new javax.swing.JPanel();
        oeste = new javax.swing.JPanel();
        image = new javax.swing.JButton();
        este = new javax.swing.JPanel();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));

        MainPanel.setPreferredSize(new java.awt.Dimension(800, 700));
        MainPanel.setLayout(new java.awt.BorderLayout());

        HeaderPanel.setPreferredSize(new java.awt.Dimension(800, 80));
        HeaderPanel.setLayout(new java.awt.BorderLayout());

        headerLabel.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        headerLabel.setText("Yeah");
        headerLabel.setToolTipText("");
        headerLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 12));
        HeaderPanel.add(headerLabel, java.awt.BorderLayout.CENTER);

        MainPanel.add(HeaderPanel, java.awt.BorderLayout.NORTH);

        WestPanel.setMaximumSize(new java.awt.Dimension(120, 39));
        WestPanel.setMinimumSize(new java.awt.Dimension(120, 39));
        WestPanel.setName(""); // NOI18N
        WestPanel.setPreferredSize(new java.awt.Dimension(120, 39));
        WestPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 25));

        Boton1.setText("Registrar");
        WestPanel.add(Boton1);

        Boton2.setText("Consultar");
        WestPanel.add(Boton2);

        Boton3.setText("Salir");
        Boton3.setPreferredSize(new java.awt.Dimension(95, 29));
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });
        WestPanel.add(Boton3);

        MainPanel.add(WestPanel, java.awt.BorderLayout.WEST);

        CenterPanel.setLayout(new java.awt.BorderLayout());

        west.setLayout(new java.awt.BorderLayout());

        north.setPreferredSize(new java.awt.Dimension(100, 93));
        north.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre");
        north.add(jLabel1, java.awt.BorderLayout.SOUTH);

        west.add(north, java.awt.BorderLayout.NORTH);

        suth.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Numero de Boleta");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        suth.add(jLabel2, java.awt.BorderLayout.NORTH);

        west.add(suth, java.awt.BorderLayout.SOUTH);

        CenterPanel.add(west, java.awt.BorderLayout.WEST);

        East.setLayout(new java.awt.BorderLayout());

        North.setPreferredSize(new java.awt.Dimension(150, 93));
        North.setLayout(new java.awt.BorderLayout());

        jTextField1.setText(" ");
        North.add(jTextField1, java.awt.BorderLayout.SOUTH);

        East.add(North, java.awt.BorderLayout.NORTH);

        South.setLayout(new java.awt.BorderLayout());

        jTextField2.setText(" ");
        South.add(jTextField2, java.awt.BorderLayout.SOUTH);

        East.add(South, java.awt.BorderLayout.SOUTH);

        CenterPanel.add(East, java.awt.BorderLayout.EAST);

        south.setPreferredSize(new java.awt.Dimension(100, 100));
        south.setLayout(new java.awt.BorderLayout());

        oeste.setMinimumSize(new java.awt.Dimension(0, 0));
        oeste.setLayout(new java.awt.BorderLayout());

        image.setText("Subir Imagen");
        oeste.add(image, java.awt.BorderLayout.SOUTH);

        south.add(oeste, java.awt.BorderLayout.CENTER);

        este.setPreferredSize(new java.awt.Dimension(135, 100));
        este.setLayout(new java.awt.BorderLayout());

        save.setText("Guardar");
        save.setPreferredSize(new java.awt.Dimension(95, 29));
        este.add(save, java.awt.BorderLayout.SOUTH);

        south.add(este, java.awt.BorderLayout.EAST);

        CenterPanel.add(south, java.awt.BorderLayout.SOUTH);

        MainPanel.add(CenterPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Boton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CopecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CopecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CopecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CopecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CopecFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel East;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel North;
    private javax.swing.JPanel South;
    private javax.swing.JPanel WestPanel;
    private javax.swing.JPanel este;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel north;
    private javax.swing.JPanel oeste;
    private javax.swing.JButton save;
    private javax.swing.JPanel south;
    private javax.swing.JPanel suth;
    private javax.swing.JPanel west;
    // End of variables declaration//GEN-END:variables
}
